# Packages required for running the examples from MPCDF's Python for HPC course:
name: pyhpc
channels:
  - conda-forge
  - nodefaults
dependencies:
  # Note: nbclassic (notebook<7) and RISE require python<=3.11 for now.
  # In case the RISE presentation mode is not necessary, newer Python
  # versions can be used and the last three lines of the present file
  # can be commented or removed.
  - python=3.11
  - pip
  - libopenblas=*=*openmp*
  - numpy
  - scipy
  - pooch
  - cython
  - pybind11
  - pandas
  - matplotlib
  - line_profiler
  - gcc_linux-64
  - gxx_linux-64
  - gfortran_linux-64
  - numba
  - jax
  - dask
  - graphviz
  - python-graphviz
  - mpich
  - mpi4py
  - hdf5=*=mpi*
  - h5py=*=mpi*
  - jupyterlab
  # Required for RISE presentation mode from nbclassic:
  - notebook<7
  - pip:
    - RISE

