name: pyhpc
channels:
  - defaults
  #- conda-forge
dependencies:
  - python=3.7
  #- libblas=*=*mkl
  - mkl
  - numpy
  - scipy
  - cython
  - matplotlib
  - pandas
  - gcc_linux-64
  - gxx_linux-64
  - gfortran_linux-64
  - numba
  - mpich
  - mpi4py
  - hdf5=*=mpi*
  - h5py=*=mpi*
  - pip
    - line-profiler
    - pybind11
