[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "HelloWorld"
version = "0.1"
description = "This is an example package"
dependencies = ["numpy"]
authors = [
  {name = "John Doe", email = "john.doe@example.mpg.de"}
]
license = {text = "PSF"}
keywords = ["hello", "world", "example"]

[project.optional-dependencies]
tests = ["pytest"]

[project.urls]
homepage = "https://example.mpg.de/HelloWorld/"

# list of executable(s) that come with the package (if applicable)
[project.scripts]
hello-world = "HelloWorld.cli:hello_world"

